Repository Sappun-Walk/Sappun, pull requests merged in 2024-01, with the labels that each got.

#4 회원가입 api 추가
  src/main/java/sparta/com/sappun/domain/TimeStamp.java
  src/main/java/sparta/com/sappun/domain/sample/controller/SampleController.java
  src/main/java/sparta/com/sappun/domain/sample/dto/response/SampleSaveRes.java
  src/main/java/sparta/com/sappun/domain/sample/entity/Sample.java
  src/main/java/sparta/com/sappun/domain/user/controller/UserController.java
  src/main/java/sparta/com/sappun/domain/user/dto/request/UserSignupReq.java
  src/main/java/sparta/com/sappun/domain/user/dto/response/UserSignupRes.java
  src/main/java/sparta/com/sappun/domain/user/entity/Role.java
  src/main/java/sparta/com/sappun/domain/user/entity/User.java
  src/main/java/sparta/com/sappun/domain/user/repository/UserRepository.java
  src/main/java/sparta/com/sappun/domain/user/service/UserService.java
  src/main/java/sparta/com/sappun/domain/user/service/UserServiceMapper.java
  src/main/java/sparta/com/sappun/domain/user/service/impl/UserServiceImpl.java
  src/main/java/sparta/com/sappun/global/exception/GlobalException.java
  src/main/java/sparta/com/sappun/global/exception/GlobalExceptionHandler.java
  src/main/java/sparta/com/sappun/global/jpa/AuditingConfig.java
  src/main/java/sparta/com/sappun/global/response/CommonResponse.java
  src/main/java/sparta/com/sappun/global/response/ResultCode.java
  src/main/java/sparta/com/sappun/global/security/WebSecurityConfig.java
  src/main/java/sparta/com/sappun/global/validator/SampleValidator.java
  src/main/java/sparta/com/sappun/global/validator/UserValidator.java
  src/test/java/sparta/com/sappun/domain/sample/controller/SampleControllerTest.java
  src/test/java/sparta/com/sappun/domain/sample/service/impl/SampleServiceImplTest.java
  src/test/java/sparta/com/sappun/domain/user/controller/UserControllerTest.java
  src/test/java/sparta/com/sappun/domain/user/repository/UserRepositoryTest.java
  src/test/java/sparta/com/sappun/domain/user/service/impl/UserServiceImplTest.java
  src/test/java/sparta/com/sappun/test/SampleTest.java
  src/test/java/sparta/com/sappun/test/UserTest.java
Labels: test, feat

#9 인가 필터 추가
  src/main/java/sparta/com/sappun/domain/user/repository/UserRepository.java
  src/main/java/sparta/com/sappun/global/exception/ExceptionHandlerFilter.java
  src/main/java/sparta/com/sappun/global/jwt/JwtAuthorizationFilter.java
  src/main/java/sparta/com/sappun/global/jwt/JwtUtil.java
  src/main/java/sparta/com/sappun/global/redis/RedisConfig.java
  src/main/java/sparta/com/sappun/global/redis/RedisUtil.java
  src/main/java/sparta/com/sappun/global/response/ResultCode.java
  src/main/java/sparta/com/sappun/global/security/UserDetailsImpl.java
  src/main/java/sparta/com/sappun/global/security/UserDetailsServiceImpl.java
  src/main/java/sparta/com/sappun/global/security/WebSecurityConfig.java
  src/main/java/sparta/com/sappun/global/validator/TokenValidator.java
  src/main/java/sparta/com/sappun/global/validator/UserValidator.java
  src/test/java/sparta/com/sappun/domain/sample/repository/SampleRepositoryTest.java
  src/test/java/sparta/com/sappun/domain/user/repository/UserRepositoryTest.java
Labels: feat

#13 로컬 로그인 api 구현
  src/main/java/sparta/com/sappun/domain/sample/service/SampleService.java
  src/main/java/sparta/com/sappun/domain/sample/service/impl/SampleServiceImpl.java
  src/main/java/sparta/com/sappun/domain/user/controller/UserController.java
  src/main/java/sparta/com/sappun/domain/user/dto/request/UserLoginReq.java
  src/main/java/sparta/com/sappun/domain/user/dto/response/UserLoginRes.java
  src/main/java/sparta/com/sappun/domain/user/entity/User.java
  src/main/java/sparta/com/sappun/domain/user/service/UserService.java
  src/main/java/sparta/com/sappun/domain/user/service/UserServiceMapper.java
  src/main/java/sparta/com/sappun/domain/user/service/impl/UserServiceImpl.java
  src/main/java/sparta/com/sappun/global/jwt/JwtAuthorizationFilter.java
  src/main/java/sparta/com/sappun/global/jwt/JwtUtil.java
  src/main/java/sparta/com/sappun/global/redis/RedisConfig.java
  src/main/java/sparta/com/sappun/global/redis/RedisUtil.java
  src/main/java/sparta/com/sappun/global/response/ResultCode.java
  src/main/java/sparta/com/sappun/global/security/UserDetailsServiceImpl.java
  src/main/java/sparta/com/sappun/global/security/WebSecurityConfig.java
  src/main/java/sparta/com/sappun/global/validator/TokenValidator.java
  src/main/java/sparta/com/sappun/global/validator/UserValidator.java
  src/test/java/sparta/com/sappun/domain/BaseMvcTest.java
  src/test/java/sparta/com/sappun/domain/sample/service/impl/SampleServiceTest.java
  src/test/java/sparta/com/sappun/domain/user/controller/UserControllerTest.java
  src/test/java/sparta/com/sappun/domain/user/service/UserServiceTest.java
Labels: test, feat

#15 로그아웃 api 구현
  src/main/java/sparta/com/sappun/domain/user/controller/UserController.java
  src/main/java/sparta/com/sappun/domain/user/dto/response/UserLogoutRes.java
  src/main/java/sparta/com/sappun/global/jwt/JwtAuthorizationFilter.java
  src/main/java/sparta/com/sappun/global/jwt/JwtUtil.java
  src/test/java/sparta/com/sappun/domain/user/controller/UserControllerTest.java
Labels: test, feat

#19 회원 탈퇴 구현
  src/main/java/sparta/com/sappun/domain/user/controller/UserController.java
  src/main/java/sparta/com/sappun/domain/user/dto/response/UserDeleteRes.java
  src/main/java/sparta/com/sappun/domain/user/repository/UserRepository.java
  src/main/java/sparta/com/sappun/domain/user/service/UserService.java
  src/test/java/sparta/com/sappun/domain/user/controller/UserControllerTest.java
  src/test/java/sparta/com/sappun/domain/user/repository/UserRepositoryTest.java
  src/test/java/sparta/com/sappun/domain/user/service/UserServiceTest.java
Labels: test, feat

#21 Feature/comment create
  src/main/java/sparta/com/sappun/domain/comment/controller/CommentController.java
  src/main/java/sparta/com/sappun/domain/comment/dto/request/CommentSaveReq.java
  src/main/java/sparta/com/sappun/domain/comment/dto/response/CommentSaveRes.java
  src/main/java/sparta/com/sappun/domain/comment/entity/Comment.java
  src/main/java/sparta/com/sappun/domain/comment/repository/CommentRepository.java
  src/main/java/sparta/com/sappun/domain/comment/service/CommentService.java
  src/main/java/sparta/com/sappun/domain/comment/service/CommentServiceMapper.java
  src/main/java/sparta/com/sappun/global/response/ResultCode.java
  src/test/java/sparta/com/sappun/domain/comment/controller/CommentControllerTest.java
  src/test/java/sparta/com/sappun/domain/comment/repository/CommentRepositoryTest.java
  src/test/java/sparta/com/sappun/domain/comment/service/CommentServiceTest.java
  src/test/java/sparta/com/sappun/test/CommentTest.java
Labels: test, feat

#25 Fix: Comment 생성시 403에러 처리
  src/main/java/sparta/com/sappun/domain/comment/service/CommentService.java
Labels: fix

#24 Feature profile update
  src/main/java/sparta/com/sappun/domain/user/controller/UserController.java
  src/main/java/sparta/com/sappun/domain/user/dto/response/UserProfileUpdateRes.java
  src/main/java/sparta/com/sappun/domain/user/repository/UserRepository.java
  src/main/java/sparta/com/sappun/domain/user/service/UserService.java
  src/main/java/sparta/com/sappun/domain/user/service/UserServiceMapper.java
  src/main/java/sparta/com/sappun/global/response/ResultCode.java
  src/main/java/sparta/com/sappun/global/validator/UserValidator.java
Labels: feat

#31 인가 필터 수정
  src/main/java/sparta/com/sappun/global/jwt/JwtAuthorizationFilter.java
Labels: perf

#32 [#26] Feat: 비밀번호 수정 API 추가
  src/main/java/sparta/com/sappun/domain/user/controller/UserController.java
  src/main/java/sparta/com/sappun/domain/user/dto/request/UserPasswordUpdateReq.java
  src/main/java/sparta/com/sappun/domain/user/dto/response/UserPasswordUpdateRes.java
  src/main/java/sparta/com/sappun/domain/user/service/UserService.java
  src/main/java/sparta/com/sappun/domain/user/service/UserServiceMapper.java
  src/main/java/sparta/com/sappun/global/response/ResultCode.java
  src/main/java/sparta/com/sappun/global/validator/UserValidator.java
Labels: feat

#35 Feature/board like
  src/main/java/sparta/com/sappun/domain/LikeComment/contorller/LikeCommentLikeController.java
  src/main/java/sparta/com/sappun/domain/LikeComment/dto/response/LikeCommentSaveRes.java
  src/main/java/sparta/com/sappun/domain/LikeComment/entity/LikeComment.java
  src/main/java/sparta/com/sappun/domain/LikeComment/repository/LikeCommentRepository.java
  src/main/java/sparta/com/sappun/domain/LikeComment/service/LikeCommentService.java
  src/main/java/sparta/com/sappun/domain/LikeComment/service/LikeCommentServiceMappper.java
  src/main/java/sparta/com/sappun/domain/comment/controller/CommentController.java
  src/main/java/sparta/com/sappun/domain/comment/repository/CommentRepository.java
  src/main/java/sparta/com/sappun/global/jwt/JwtAuthorizationFilter.java
  src/test/java/sparta/com/sappun/domain/LikeComment/contorller/LikeCommentLikeControllerTest.java
  src/test/java/sparta/com/sappun/domain/LikeComment/repository/LikeCommentRepositoryTest.java
  src/test/java/sparta/com/sappun/domain/LikeComment/service/LikeCommentServiceTest.java
  src/test/java/sparta/com/sappun/test/LikeCommentTest.java
Labels: test, feat

#41 아이디/닉네임 중복 확인 API 분리
  src/main/java/sparta/com/sappun/domain/user/controller/UserController.java
  src/main/java/sparta/com/sappun/domain/user/dto/request/NicknameVerifyReq.java
  src/main/java/sparta/com/sappun/domain/user/dto/request/UsernameVerifyReq.java
  src/main/java/sparta/com/sappun/domain/user/dto/response/NicknameVerifyRes.java
  src/main/java/sparta/com/sappun/domain/user/dto/response/UsernameVerifyRes.java
  src/main/java/sparta/com/sappun/domain/user/service/UserService.java
Labels: feat

#46 Feature/report comment
  src/main/java/sparta/com/sappun/domain/ReportComment/contorller/ReportCommentController.java
  src/main/java/sparta/com/sappun/domain/ReportComment/dto/request/ReportCommentReq.java
  src/main/java/sparta/com/sappun/domain/ReportComment/dto/response/ReportCommentRes.java
  src/main/java/sparta/com/sappun/domain/ReportComment/entity/ReportComment.java
  src/main/java/sparta/com/sappun/domain/ReportComment/repository/ReportCommentRepository.java
  src/main/java/sparta/com/sappun/domain/ReportComment/service/ReportCommentService.java
  src/main/java/sparta/com/sappun/domain/ReportComment/service/ReportCommentServiceMapper.java
Labels: feat

#50 user 도메인 관련 수정, BoardServiceMapper 오류 수정
  src/main/java/sparta/com/sappun/domain/ReportBoard/service/ReportBoardService.java
  src/main/java/sparta/com/sappun/domain/ReportComment/controller/ReportCommentController.java
  src/main/java/sparta/com/sappun/domain/ReportComment/service/ReportCommentService.java
  src/main/java/sparta/com/sappun/domain/board/service/BoardService.java
  src/main/java/sparta/com/sappun/domain/board/service/BoardServiceMapper.java
  src/main/java/sparta/com/sappun/domain/comment/service/CommentService.java
  src/main/java/sparta/com/sappun/domain/user/controller/UserController.java
  src/main/java/sparta/com/sappun/domain/user/dto/request/NicknameVerifyReq.java
  src/main/java/sparta/com/sappun/domain/user/dto/request/UserLoginReq.java
  src/main/java/sparta/com/sappun/domain/user/dto/request/UserPasswordUpdateReq.java
  src/main/java/sparta/com/sappun/domain/user/dto/request/UserProfileUpdateReq.java
  src/main/java/sparta/com/sappun/domain/user/service/UserService.java
  src/main/java/sparta/com/sappun/global/validator/CommentValidator.java
Labels: fix, refactor

#56 jacoco, email 필드 추가
  build.gradle
  src/main/java/sparta/com/sappun/domain/user/entity/User.java
Labels: build

#57 Board 수정, 삭제 API 구현
  src/main/java/sparta/com/sappun/domain/board/controller/BoardController.java
  src/main/java/sparta/com/sappun/domain/board/dto/request/BoardUpdateReq.java
  src/main/java/sparta/com/sappun/domain/board/dto/response/BoardDeleteRes.java
  src/main/java/sparta/com/sappun/domain/board/dto/response/BoardUpdateRes.java
  src/main/java/sparta/com/sappun/domain/board/entity/Board.java
  src/main/java/sparta/com/sappun/domain/board/service/BoardService.java
  src/main/java/sparta/com/sappun/domain/board/service/BoardServiceMapper.java
  src/main/java/sparta/com/sappun/global/validator/BoardValidator.java
Labels: feat

#62 사용자 도메인에 이메일 추가
  src/main/java/sparta/com/sappun/domain/user/dto/request/UserSignupReq.java
  src/main/java/sparta/com/sappun/domain/user/dto/response/UserProfileRes.java
  src/main/java/sparta/com/sappun/domain/user/dto/response/UserProfileUpdateRes.java
  src/main/java/sparta/com/sappun/domain/user/repository/UserRepository.java
  src/main/java/sparta/com/sappun/domain/user/service/UserService.java
  src/main/java/sparta/com/sappun/global/response/ResultCode.java
  src/main/java/sparta/com/sappun/global/validator/UserValidator.java
  src/test/java/sparta/com/sappun/domain/user/controller/UserControllerTest.java
  src/test/java/sparta/com/sappun/domain/user/repository/UserRepositoryTest.java
  src/test/java/sparta/com/sappun/domain/user/service/UserServiceTest.java
  src/test/java/sparta/com/sappun/test/UserTest.java
Labels: feat

#63 사용자 점수 기능 추가
  src/main/java/sparta/com/sappun/domain/LikeBoard/entity/LikeBoard.java
  src/main/java/sparta/com/sappun/domain/LikeBoard/service/LikeBoardService.java
  src/main/java/sparta/com/sappun/domain/LikeComment/entity/LikeComment.java
  src/main/java/sparta/com/sappun/domain/LikeComment/service/LikeCommentService.java
  src/main/java/sparta/com/sappun/domain/ReportBoard/entity/ReportBoard.java
  src/main/java/sparta/com/sappun/domain/ReportBoard/service/ReportBoardService.java
  src/main/java/sparta/com/sappun/domain/ReportComment/entity/ReportComment.java
  src/main/java/sparta/com/sappun/domain/ReportComment/service/ReportCommentService.java
  src/main/java/sparta/com/sappun/domain/board/service/BoardService.java
  src/main/java/sparta/com/sappun/domain/comment/dto/request/CommentSaveReq.java
  src/main/java/sparta/com/sappun/domain/comment/service/CommentService.java
  src/main/java/sparta/com/sappun/domain/user/dto/response/UserLoginRes.java
  src/main/java/sparta/com/sappun/domain/user/dto/response/UserProfileRes.java
  src/main/java/sparta/com/sappun/domain/user/dto/response/UserProfileUpdateRes.java
  src/main/java/sparta/com/sappun/domain/user/entity/User.java
  src/main/java/sparta/com/sappun/domain/user/service/UserService.java
  src/test/java/sparta/com/sappun/domain/user/repository/UserRepositoryTest.java
  src/test/java/sparta/com/sappun/domain/user/service/UserServiceTest.java
  src/test/java/sparta/com/sappun/test/UserTest.java
Labels: feat

#66 관리자의 게시글, 댓글 신고 취소 기능 추가
  src/main/java/sparta/com/sappun/domain/ReportBoard/contorller/ReportBoardController.java
  src/main/java/sparta/com/sappun/domain/ReportBoard/dto/request/ReportBoardReq.java
  src/main/java/sparta/com/sappun/domain/ReportBoard/dto/response/DeleteReportBoardRes.java
  src/main/java/sparta/com/sappun/domain/ReportBoard/repository/ReportBoardRepository.java
  src/main/java/sparta/com/sappun/domain/ReportBoard/service/ReportBoardService.java
  src/main/java/sparta/com/sappun/domain/ReportComment/controller/ReportCommentController.java
  src/main/java/sparta/com/sappun/domain/ReportComment/dto/response/DeleteReportCommentRes.java
  src/main/java/sparta/com/sappun/domain/ReportComment/repository/ReportCommentRepository.java
  src/main/java/sparta/com/sappun/domain/ReportComment/service/ReportCommentService.java
  src/main/java/sparta/com/sappun/global/response/ResultCode.java
  src/main/java/sparta/com/sappun/global/security/CustomAccessDeniedHandler.java
  src/main/java/sparta/com/sappun/global/security/WebSecurityConfig.java
  src/main/java/sparta/com/sappun/global/validator/BoardValidator.java
  src/main/java/sparta/com/sappun/global/validator/CommentValidator.java
Labels: feat

#68 좋아요. 신고 중복 불가능하도록 수정
  src/main/java/sparta/com/sappun/domain/LikeBoard/contorller/LikeBoardLikeController.java
  src/main/java/sparta/com/sappun/domain/LikeBoard/repository/LikeBoardRepository.java
  src/main/java/sparta/com/sappun/domain/LikeBoard/service/LikeBoardService.java
  src/main/java/sparta/com/sappun/domain/LikeComment/contorller/LikeCommentLikeController.java
  src/main/java/sparta/com/sappun/domain/LikeComment/repository/LikeCommentRepository.java
  src/main/java/sparta/com/sappun/domain/LikeComment/service/LikeCommentService.java
  src/main/java/sparta/com/sappun/domain/ReportBoard/contorller/ReportBoardController.java
  src/main/java/sparta/com/sappun/domain/ReportBoard/repository/ReportBoardRepository.java
  src/main/java/sparta/com/sappun/domain/ReportBoard/service/ReportBoardService.java
  src/main/java/sparta/com/sappun/domain/ReportComment/controller/ReportCommentController.java
  src/main/java/sparta/com/sappun/domain/ReportComment/repository/ReportCommentRepository.java
  src/main/java/sparta/com/sappun/domain/ReportComment/service/ReportCommentService.java
  src/main/java/sparta/com/sappun/global/response/ResultCode.java
  src/main/java/sparta/com/sappun/global/validator/ReportBoardValidator.java
  src/main/java/sparta/com/sappun/global/validator/ReportCommentValidator.java
  src/test/java/sparta/com/sappun/domain/LikeComment/contorller/LikeCommentLikeControllerTest.java
  src/test/java/sparta/com/sappun/domain/LikeComment/service/LikeCommentServiceTest.java
  src/test/java/sparta/com/sappun/domain/ReportComment/contorller/ReportCommentControllerTest.java
  src/test/java/sparta/com/sappun/domain/ReportComment/service/ReportCommentServiceTest.java
Labels: feat

#70 [#69] Fix: Dto에 빠진 필드 추가
  src/main/java/sparta/com/sappun/domain/user/dto/response/UserProfileRes.java
  src/main/java/sparta/com/sappun/domain/user/dto/response/UserProfileUpdateRes.java
Labels: fix

#72 Feature/test like board
  src/main/java/sparta/com/sappun/domain/LikeBoard/contorller/LikeBoardController.java
  src/main/java/sparta/com/sappun/domain/LikeComment/contorller/LikeCommentController.java
  src/test/java/sparta/com/sappun/domain/LikeBoard/contorller/LikeBoardControllerTest.java
  src/test/java/sparta/com/sappun/domain/LikeBoard/repository/LikeBoardRepositoryTest.java
  src/test/java/sparta/com/sappun/domain/LikeBoard/service/LikeBoardServiceTest.java
  src/test/java/sparta/com/sappun/domain/LikeComment/contorller/LikeCommentControllerTest.java
  src/test/java/sparta/com/sappun/domain/ReportBoard/contorller/ReportBoardControllerTest.java
  src/test/java/sparta/com/sappun/domain/ReportBoard/repository/ReportBoardRepositoryTest.java
  src/test/java/sparta/com/sappun/domain/ReportBoard/service/ReportBoardServiceTest.java
  src/test/java/sparta/com/sappun/test/BoardTest.java
  src/test/java/sparta/com/sappun/test/LikeBoardTest.java
  src/test/java/sparta/com/sappun/test/ReportBoardTest.java
Labels: test

#77 AWS S3 기능 추가
  src/main/java/sparta/com/sappun/global/response/ResultCode.java
  src/main/java/sparta/com/sappun/global/validator/S3Validator.java
  src/main/java/sparta/com/sappun/infra/s3/S3Config.java
  src/main/java/sparta/com/sappun/infra/s3/S3Util.java
  src/main/resources/application.yml
Labels: fix, feat

#88 [#87] Refactor: Delete comment 관련 Refactor
  src/main/java/sparta/com/sappun/domain/comment/controller/CommentController.java
  src/main/java/sparta/com/sappun/domain/comment/dto/request/CommentDeleteReq.java
  src/main/java/sparta/com/sappun/domain/comment/service/CommentService.java
Labels: refactor

#93 프로필 사진 관련 로직 추가
  .gitignore
  src/main/java/sparta/com/sappun/domain/user/controller/UserController.java
  src/main/java/sparta/com/sappun/domain/user/dto/request/UserProfileUpdateReq.java
  src/main/java/sparta/com/sappun/domain/user/entity/User.java
  src/main/java/sparta/com/sappun/domain/user/service/KakaoService.java
  src/main/java/sparta/com/sappun/domain/user/service/NaverService.java
  src/main/java/sparta/com/sappun/domain/user/service/UserService.java
  src/main/java/sparta/com/sappun/global/jwt/JwtUtil.java
  src/main/resources/application.yml
  src/main/resources/images/image1.jpg
  src/test/java/sparta/com/sappun/domain/user/controller/UserControllerTest.java
  src/test/java/sparta/com/sappun/domain/user/service/UserServiceTest.java
  src/test/java/sparta/com/sappun/test/UserTest.java
Labels: test, feat

#98 [#81] Feat: 지역별 게시글 목록 조회 페이징 처리
  src/main/java/sparta/com/sappun/domain/board/controller/BoardController.java
  src/main/java/sparta/com/sappun/domain/board/entity/Board.java
  src/main/java/sparta/com/sappun/domain/board/repository/BoardRepository.java
  src/main/java/sparta/com/sappun/domain/board/service/BoardService.java
  src/main/java/sparta/com/sappun/domain/board/service/BoardServiceMapper.java
  src/main/java/sparta/com/sappun/domain/likeBoard/service/LikeBoardService.java
  src/main/java/sparta/com/sappun/domain/reportBoard/service/ReportBoardService.java
  src/test/java/sparta/com/sappun/test/BoardTest.java
Labels: feat

#99 테스트코드 작성
  src/main/java/sparta/com/sappun/global/validator/UserValidator.java
  src/test/java/sparta/com/sappun/domain/user/controller/UserControllerTest.java
  src/test/java/sparta/com/sappun/domain/user/service/UserServiceTest.java
  src/test/java/sparta/com/sappun/test/UserTest.java
Labels: test

#97 [#96] Feat: Comment 사진 추가 로직 구현
  src/main/java/sparta/com/sappun/domain/comment/controller/CommentController.java
  src/main/java/sparta/com/sappun/domain/comment/dto/request/CommentSaveReq.java
  src/main/java/sparta/com/sappun/domain/comment/dto/request/CommentUpdateReq.java
  src/main/java/sparta/com/sappun/domain/comment/entity/Comment.java
  src/main/java/sparta/com/sappun/domain/comment/service/CommentService.java
  src/test/java/sparta/com/sappun/test/CommentTest.java
Labels: feat

#101 토큰 쿠키에 담도록 수정
  src/main/java/sparta/com/sappun/domain/user/controller/KakaoController.java
  src/main/java/sparta/com/sappun/domain/user/controller/NaverController.java
  src/main/java/sparta/com/sappun/domain/user/controller/UserController.java
  src/main/java/sparta/com/sappun/domain/user/service/KakaoService.java
  src/main/java/sparta/com/sappun/domain/user/service/NaverService.java
  src/main/java/sparta/com/sappun/global/jwt/JwtAuthorizationFilter.java
  src/main/java/sparta/com/sappun/global/jwt/JwtUtil.java
  src/test/java/sparta/com/sappun/domain/user/controller/UserControllerTest.java
Labels: feat

#107 [#106] Fix: tokens 오타 수정
  src/main/java/sparta/com/sappun/domain/user/service/KakaoService.java
  src/main/java/sparta/com/sappun/domain/user/service/NaverService.java
Labels: fix

#109 [#108] Fix: 한글명 파일일때 파일을 찾지못하는 오류 해결
  src/main/java/sparta/com/sappun/domain/comment/service/CommentService.java
  src/main/java/sparta/com/sappun/infra/s3/S3Util.java
  src/test/java/sparta/com/sappun/domain/comment/service/CommentServiceTest.java
Labels: fix

#110 프로필 조회 페이지
  src/main/java/sparta/com/sappun/domain/user/controller/UserController.java
  src/main/java/sparta/com/sappun/global/jwt/JwtAuthorizationFilter.java
  src/main/resources/static/images/image1.jpg
  src/main/resources/static/images/logo.png
  src/main/resources/templates/profile.html
  src/test/java/sparta/com/sappun/domain/user/controller/UserControllerTest.java
  src/test/java/sparta/com/sappun/domain/user/service/UserServiceTest.java
Labels: front

#112 [#89] test:메인 페이지 프론트엔드 코드 작성
  src/main/java/sparta/com/sappun/domain/board/controller/BoardController.java
  src/main/resources/templates/mainPage.html
Labels: front

#116 Feature/comment test code
  src/main/java/sparta/com/sappun/domain/comment/dto/response/CommentGetRes.java
  src/main/java/sparta/com/sappun/domain/comment/dto/response/CommentSaveRes.java
  src/main/java/sparta/com/sappun/domain/comment/entity/Comment.java
  src/main/java/sparta/com/sappun/domain/comment/service/CommentService.java
  src/main/java/sparta/com/sappun/domain/likeComment/service/LikeCommentService.java
  src/main/java/sparta/com/sappun/domain/reportComment/service/ReportCommentService.java
  src/test/java/sparta/com/sappun/domain/comment/controller/CommentControllerTest.java
  src/test/java/sparta/com/sappun/domain/comment/repository/CommentRepositoryTest.java
  src/test/java/sparta/com/sappun/domain/comment/service/CommentServiceTest.java
  src/test/java/sparta/com/sappun/domain/likeComment/repository/LikeCommentRepositoryTest.java
  src/test/java/sparta/com/sappun/domain/reportComment/contorller/ReportCommentControllerTest.java
  src/test/java/sparta/com/sappun/domain/reportComment/repository/ReportCommentRepositoryTest.java
  src/test/java/sparta/com/sappun/domain/reportComment/service/ReportCommentServiceTest.java
  src/test/java/sparta/com/sappun/test/BoardTest.java
  src/test/java/sparta/com/sappun/test/CommentTest.java
  src/test/java/sparta/com/sappun/test/ReportCommentTest.java
Labels: test, feat

#119 [#103,114] Feat, Fix: Board Test Code 작성 / Board 관련 오류 수정
  src/main/java/sparta/com/sappun/domain/board/controller/BoardController.java
  src/main/java/sparta/com/sappun/domain/board/dto/request/BoardSaveReq.java
  src/main/java/sparta/com/sappun/domain/board/entity/Board.java
  src/main/java/sparta/com/sappun/domain/board/service/BoardService.java
  src/test/java/sparta/com/sappun/domain/board/controller/BoardControllerTest.java
  src/test/java/sparta/com/sappun/domain/board/repository/BoardRepositoryTest.java
  src/test/java/sparta/com/sappun/domain/board/service/BoardServiceTest.java
  src/test/java/sparta/com/sappun/test/BoardTest.java
Labels: fix, test

#124 [#104,105] 게시글 상세 조회, 작성 페이지 구현
  src/main/resources/templates/getBoardDetail.html
  src/main/resources/templates/saveBoardPage1.html
  src/main/resources/templates/saveBoardPage2.html
Labels: front

#125 Feature/login sign page
  src/main/java/sparta/com/sappun/domain/user/controller/KakaoController.java
  src/main/java/sparta/com/sappun/domain/user/controller/NaverController.java
  src/main/java/sparta/com/sappun/domain/user/controller/UserController.java
  src/main/resources/css/style.css
  src/main/resources/templates/login.html
  src/main/resources/templates/signup.html
Labels: front

#126 [#122] front: 비밀번호 수정 페이지 뼈대 구현
  src/main/resources/templates/pwUpdate.html
Labels: front

#130 [#128] Front: 로그인 페이지 연결 구현
  src/main/java/sparta/com/sappun/domain/user/controller/UserController.java
  src/main/java/sparta/com/sappun/global/security/WebSecurityConfig.java
  src/main/resources/templates/login.html
Labels: front

#131 프로필 수정 api 요청 오류 수정
  src/main/java/sparta/com/sappun/domain/user/controller/UserController.java
  src/main/java/sparta/com/sappun/domain/user/dto/request/UserProfileUpdateReq.java
  src/main/java/sparta/com/sappun/domain/user/service/UserService.java
  src/main/resources/templates/profile-update.html
Labels: front

#133 [#132] front: 비밀번호 수정 페이지 버튼 연결
  src/main/java/sparta/com/sappun/domain/user/service/UserService.java
  src/main/java/sparta/com/sappun/global/jwt/JwtAuthorizationFilter.java
  src/main/resources/templates/mainPage.html
  src/main/resources/templates/pwUpdate.html
Labels: front

#135 [#134] Front: 로그인 페이지 연결 구현
  src/main/java/sparta/com/sappun/domain/user/controller/UserController.java
  src/main/java/sparta/com/sappun/domain/user/dto/request/UserSignupReq.java
  src/main/java/sparta/com/sappun/global/jwt/JwtAuthorizationFilter.java
  src/main/resources/css/style.css
  src/main/resources/templates/login.html
  src/main/resources/templates/signup.html
Labels: front

#138 [#136] Front: 회원가입 페이지 연결 구현
  src/main/java/sparta/com/sappun/domain/user/controller/UserController.java
  src/main/java/sparta/com/sappun/domain/user/dto/request/UserSignupReq.java
  src/main/java/sparta/com/sappun/global/security/WebSecurityConfig.java
  src/main/resources/templates/signup.html
Labels: front

#144 Feature/testpage
  src/main/java/sparta/com/sappun/domain/board/controller/BoardController.java
  src/main/java/sparta/com/sappun/global/jwt/JwtAuthorizationFilter.java
  src/main/resources/templates/mainPage.html
  src/main/resources/templates/regionPage.html
Labels: front

#147 회원 탈퇴 로직 수정
  src/main/java/sparta/com/sappun/domain/board/repository/BoardRepository.java
  src/main/java/sparta/com/sappun/domain/comment/repository/CommentRepository.java
  src/main/java/sparta/com/sappun/domain/likeBoard/repository/LikeBoardRepository.java
  src/main/java/sparta/com/sappun/domain/likeComment/repository/LikeCommentRepository.java
  src/main/java/sparta/com/sappun/domain/reportBoard/repository/ReportBoardRepository.java
  src/main/java/sparta/com/sappun/domain/reportComment/repository/ReportCommentRepository.java
  src/main/java/sparta/com/sappun/domain/user/service/UserService.java
  src/test/java/sparta/com/sappun/domain/board/controller/BoardControllerTest.java
  src/test/java/sparta/com/sappun/domain/board/repository/BoardRepositoryTest.java
  src/test/java/sparta/com/sappun/domain/board/service/BoardServiceTest.java
  src/test/java/sparta/com/sappun/domain/comment/repository/CommentRepositoryTest.java
  src/test/java/sparta/com/sappun/domain/likeBoard/repository/LikeBoardRepositoryTest.java
  src/test/java/sparta/com/sappun/domain/likeComment/repository/LikeCommentRepositoryTest.java
  src/test/java/sparta/com/sappun/domain/reportBoard/repository/ReportBoardRepositoryTest.java
  src/test/java/sparta/com/sappun/domain/reportComment/repository/ReportCommentRepositoryTest.java
  src/test/java/sparta/com/sappun/domain/user/service/UserServiceTest.java
  src/test/java/sparta/com/sappun/test/BoardTest.java
Labels: fix, test

#148 [#143] feat:게시판 글쓰기 페이지 이동
  src/main/resources/templates/regionPage.html
Labels: feat, front

#152 Feature/login sign page
  src/main/resources/css/style.css
  src/main/resources/templates/login.html
  src/main/resources/templates/signup.html
Labels: front

#156 쿠키 삭제 추가
  src/main/resources/templates/login.html
  src/main/resources/templates/profile-update.html
  src/main/resources/templates/profile.html
  src/main/resources/templates/pwUpdate.html
  src/main/resources/templates/signup.html
Labels: front

#161 [#160] front:지역 게시판 수정
  src/main/java/sparta/com/sappun/domain/board/controller/BoardController.java
  src/main/resources/templates/mainPage.html
  src/main/resources/templates/regionPage.html
Labels: front

#163 샘플 코드 삭제
  src/main/java/sparta/com/sappun/domain/sample/controller/SampleController.java
  src/main/java/sparta/com/sappun/domain/sample/dto/request/SampleDeleteReq.java
  src/main/java/sparta/com/sappun/domain/sample/dto/request/SampleSaveReq.java
  src/main/java/sparta/com/sappun/domain/sample/dto/request/SampleUpdateReq.java
  src/main/java/sparta/com/sappun/domain/sample/dto/response/SampleDeleteRes.java
  src/main/java/sparta/com/sappun/domain/sample/dto/response/SampleGetRes.java
  src/main/java/sparta/com/sappun/domain/sample/dto/response/SampleSaveRes.java
  src/main/java/sparta/com/sappun/domain/sample/dto/response/SampleUpdateRes.java
  src/main/java/sparta/com/sappun/domain/sample/entity/Sample.java
  src/main/java/sparta/com/sappun/domain/sample/repository/SampleRepository.java
  src/main/java/sparta/com/sappun/domain/sample/service/SampleService.java
  src/main/java/sparta/com/sappun/domain/sample/service/SampleServiceMapper.java
  src/main/java/sparta/com/sappun/global/validator/SampleValidator.java
  src/main/resources/templates/mainPage.html
  src/test/java/sparta/com/sappun/domain/sample/controller/SampleControllerTest.java
  src/test/java/sparta/com/sappun/domain/sample/repository/SampleRepositoryTest.java
  src/test/java/sparta/com/sappun/domain/sample/service/impl/SampleServiceTest.java
  src/test/java/sparta/com/sappun/test/SampleTest.java
Labels: remove

#165 [#164] front: 게시글 단건 조회, 작성, 수정, 삭제 연결
  src/main/java/sparta/com/sappun/domain/board/controller/BoardController.java
  src/main/java/sparta/com/sappun/domain/board/dto/request/BoardSaveReq.java
  src/main/java/sparta/com/sappun/domain/board/dto/request/BoardUpdateReq.java
  src/main/java/sparta/com/sappun/domain/board/entity/Board.java
  src/main/java/sparta/com/sappun/domain/board/service/BoardService.java
  src/main/java/sparta/com/sappun/domain/comment/controller/CommentController.java
  src/main/java/sparta/com/sappun/global/jwt/JwtAuthorizationFilter.java
  src/main/java/sparta/com/sappun/global/security/WebSecurityConfig.java
  src/main/resources/templates/getBoardDetail.html
  src/main/resources/templates/saveBoardPage.html
  src/main/resources/templates/updateBoardPage.html
  src/test/java/sparta/com/sappun/domain/board/repository/BoardRepositoryTest.java
Labels: front

#167 단일 조회 신고 버튼 추가
  src/main/java/sparta/com/sappun/domain/board/controller/BoardController.java
  src/main/java/sparta/com/sappun/domain/reportBoard/controller/ReportBoardController.java
  src/main/java/sparta/com/sappun/domain/reportComment/controller/ReportCommentController.java
  src/main/java/sparta/com/sappun/global/jwt/JwtAuthorizationFilter.java
  src/main/java/sparta/com/sappun/global/security/WebSecurityConfig.java
  src/main/resources/templates/getBoardDetail.html
  src/main/resources/templates/profile.html
Labels: front

#169 [#168] front: 비밀번호 수정 페이지 CSS 구현
  src/main/resources/templates/pwUpdate.html
Labels: front

#171 [#170] front: 비밀번호 수정 페이지 로고 클릭 연결페이지 수정
  src/main/resources/templates/pwUpdate.html
Labels: front

#175 게시글 단일 조회의 좋아요, 신고 버튼 기능 추가
  src/main/java/sparta/com/sappun/domain/likeBoard/controller/LikeBoardController.java
  src/main/resources/templates/getBoardDetail.html
Labels: front

#177 [#176] front: 댓글 삭제 구현 및 로그인 여부 확인 추가
  src/main/java/sparta/com/sappun/domain/board/controller/BoardController.java
  src/main/resources/templates/getBoardDetail.html
Labels: front

#180 게시글 단일 조회 댓글 수정 구현
  src/main/java/sparta/com/sappun/domain/comment/controller/CommentController.java
  src/main/java/sparta/com/sappun/domain/comment/dto/request/CommentUpdateReq.java
  src/main/java/sparta/com/sappun/domain/comment/service/CommentService.java
  src/main/resources/templates/getBoardDetail.html
Labels: front

#183 게시글 수정 페이지 구현
  src/main/java/sparta/com/sappun/domain/board/controller/BoardController.java
  src/main/java/sparta/com/sappun/domain/board/service/BoardService.java
  src/main/resources/templates/getBoardDetail.html
  src/main/resources/templates/saveBoardPage.html
  src/main/resources/templates/updateBoardPage.html
Labels: front

#184 Feature/main page
  src/main/java/sparta/com/sappun/domain/board/entity/RegionEnum.java
  src/main/resources/templates/login.html
  src/main/resources/templates/mainPage.html
  src/main/resources/templates/signup.html
Labels: front

#186 메인 페이지 관리 버튼 추가
  src/main/java/sparta/com/sappun/domain/board/controller/BoardController.java
  src/main/resources/templates/mainPage.html
Labels: front

#188 [#187] Front: 지역페이지 Css 및 사이드바 구현
  src/main/java/sparta/com/sappun/domain/board/controller/BoardController.java
  src/main/resources/templates/mainPage.html
  src/main/resources/templates/regionPage.html
Labels: front

#190 게시글 작성 페이지 구현
  src/main/java/sparta/com/sappun/domain/board/controller/BoardController.java
  src/main/java/sparta/com/sappun/domain/board/service/BoardService.java
  src/main/resources/templates/mainPage.html
  src/main/resources/templates/saveBoardPage.html
  src/main/resources/templates/updateBoardPage.html
Labels: front

#192 페이지 전체 로그아웃 수정
  src/main/java/sparta/com/sappun/domain/board/controller/BoardController.java
  src/main/resources/templates/getBoardDetail.html
  src/main/resources/templates/mainPage.html
  src/main/resources/templates/profile-update.html
  src/main/resources/templates/profile.html
  src/main/resources/templates/regionPage.html
  src/main/resources/templates/saveBoardPage.html
  src/main/resources/templates/updateBoardPage.html
Labels: front

#194 신고 게시글 조회 페이징 적용
  src/main/java/sparta/com/sappun/domain/board/controller/BoardController.java
  src/main/java/sparta/com/sappun/domain/board/dto/response/BoardListGetRes.java
  src/main/java/sparta/com/sappun/domain/board/dto/response/BoardSaveRes.java
  src/main/java/sparta/com/sappun/domain/board/dto/response/BoardToListGetRes.java
  src/main/java/sparta/com/sappun/domain/board/dto/response/BoardToReportGetRes.java
  src/main/java/sparta/com/sappun/domain/board/dto/response/BoardToReportListGetRes.java
  src/main/java/sparta/com/sappun/domain/board/dto/response/BoardUpdateRes.java
  src/main/java/sparta/com/sappun/domain/board/service/BoardService.java
  src/main/java/sparta/com/sappun/domain/board/service/BoardServiceMapper.java
  src/main/java/sparta/com/sappun/domain/reportBoard/controller/ReportBoardController.java
  src/main/java/sparta/com/sappun/domain/reportBoard/dto/response/ReportBoardGetRes.java
  src/main/java/sparta/com/sappun/domain/reportBoard/dto/response/ReportBoardListGetRes.java
  src/main/java/sparta/com/sappun/domain/reportBoard/repository/ReportBoardRepository.java
  src/main/java/sparta/com/sappun/domain/reportBoard/service/ReportBoardService.java
  src/main/java/sparta/com/sappun/domain/reportBoard/service/ReportBoardServiceMapper.java
  src/test/java/sparta/com/sappun/domain/board/controller/BoardControllerTest.java
  src/test/java/sparta/com/sappun/domain/reportBoard/repository/ReportBoardRepositoryTest.java
Labels: feat

#196 Feature/login sign page
  src/main/resources/templates/mainPage.html
  src/main/resources/templates/profile-update.html
  src/main/resources/templates/pwUpdate.html
Labels: front

#198 신고된 게시글 조회 페이지 구현
  src/main/java/sparta/com/sappun/domain/board/controller/BoardController.java
  src/main/java/sparta/com/sappun/domain/reportBoard/controller/ReportBoardController.java
  src/main/java/sparta/com/sappun/domain/user/dto/request/UserSignupReq.java
  src/main/java/sparta/com/sappun/domain/user/dto/request/UsernameVerifyReq.java
  src/main/resources/templates/regionPage.html
  src/main/resources/templates/reportBoardPage.html
  src/main/resources/templates/signup.html
Labels: front

#201 신고된 댓글 조회 페이징 처리
  src/main/java/sparta/com/sappun/domain/comment/dto/response/CommentToReportListGetRes.java
  src/main/java/sparta/com/sappun/domain/reportBoard/controller/ReportBoardController.java
  src/main/java/sparta/com/sappun/domain/reportComment/controller/ReportCommentController.java
  src/main/java/sparta/com/sappun/domain/reportComment/dto/response/CommentToReportGetRes.java
  src/main/java/sparta/com/sappun/domain/reportComment/dto/response/ReportCommentGetRes.java
  src/main/java/sparta/com/sappun/domain/reportComment/dto/response/ReportCommentListGetRes.java
  src/main/java/sparta/com/sappun/domain/reportComment/repository/ReportCommentRepository.java
  src/main/java/sparta/com/sappun/domain/reportComment/service/ReportCommentService.java
  src/main/java/sparta/com/sappun/domain/reportComment/service/ReportCommentServiceMapper.java
  src/main/resources/templates/reportBoardPage.html
  src/test/java/sparta/com/sappun/domain/reportComment/contorller/ReportCommentControllerTest.java
  src/test/java/sparta/com/sappun/domain/reportComment/repository/ReportCommentRepositoryTest.java
Labels: feat

#204 신고된 댓글 조회 페이지 구현
  src/main/resources/templates/reportCommentPage.html
Labels: front

#209 댓글 등록 구현
  src/main/java/sparta/com/sappun/domain/comment/controller/CommentController.java
  src/main/java/sparta/com/sappun/domain/comment/dto/request/CommentSaveReq.java
  src/main/resources/templates/getBoardDetail.html
Labels: front

#211 게시글과 댓글 삭제 오류 수정
  src/main/java/sparta/com/sappun/domain/likeBoard/entity/LikeBoard.java
  src/main/java/sparta/com/sappun/domain/likeComment/entity/LikeComment.java
  src/main/java/sparta/com/sappun/domain/reportBoard/entity/ReportBoard.java
  src/main/java/sparta/com/sappun/domain/reportComment/entity/ReportComment.java
  src/main/resources/templates/getBoardDetail.html
Labels: fix

#212 게시글과 댓글 삭제 권한 오류 수정
  src/main/java/sparta/com/sappun/domain/board/service/BoardService.java
  src/main/java/sparta/com/sappun/domain/comment/service/CommentService.java
Labels: fix

#214 js, css 코드 분리, url 수정
  src/main/java/sparta/com/sappun/domain/board/controller/BoardController.java
  src/main/java/sparta/com/sappun/domain/comment/controller/CommentController.java
  src/main/java/sparta/com/sappun/domain/comment/dto/request/CommentSaveReq.java
  src/main/java/sparta/com/sappun/domain/user/controller/UserController.java
  src/main/resources/static/css/getBoardDetail.css
  src/main/resources/static/css/login.css
  src/main/resources/static/css/mainPage.css
  src/main/resources/static/css/profile.css
  src/main/resources/static/css/profileUpdate.css
  src/main/resources/static/css/pwUpdate.css
  src/main/resources/static/css/regionPage.css
  src/main/resources/static/css/reportBoardPage.css
  src/main/resources/static/css/reportCommentPage.css
  src/main/resources/static/css/saveBoardPage.css
  src/main/resources/static/css/signup.css
  src/main/resources/static/css/updateBoardPage.css
  src/main/resources/static/js/basic.js
  src/main/resources/static/login.html
  src/main/resources/templates/getBoardDetail.html
  src/main/resources/templates/login.html
  src/main/resources/templates/mainPage.html
  src/main/resources/templates/profile-update.html
  src/main/resources/templates/profile.html
  src/main/resources/templates/profileUpdate.html
  src/main/resources/templates/pwUpdate.html
  src/main/resources/templates/regionPage.html
  src/main/resources/templates/reportBoardPage.html
  src/main/resources/templates/reportCommentPage.html
  src/main/resources/templates/saveBoardPage.html
  src/main/resources/templates/signup.html
  src/main/resources/templates/updateBoardPage.html
  src/test/java/sparta/com/sappun/domain/comment/controller/CommentControllerTest.java
Labels: refactor

#216 게시글 조회 페이지 수정
  src/main/java/sparta/com/sappun/domain/board/controller/BoardController.java
  src/main/resources/templates/getBoardDetail.html
  src/main/resources/templates/saveBoardPage.html
Labels: front

#220 [#219] feat: 게시글 신고 누적 5회 시 게시글 목록에서 제외(Best3, 지역별 게시판)
  src/main/java/sparta/com/sappun/domain/board/repository/BoardRepository.java
  src/main/java/sparta/com/sappun/domain/board/service/BoardService.java
  src/test/java/sparta/com/sappun/domain/board/repository/BoardRepositoryTest.java
Labels: feat

#222 수정 시 기존 데이터를 보이도록 수정
  src/main/java/sparta/com/sappun/domain/board/controller/BoardController.java
  src/main/java/sparta/com/sappun/domain/board/service/BoardService.java
  src/main/resources/static/css/updateBoardPage.css
  src/main/resources/static/js/basic.js
  src/main/resources/templates/getBoardDetail.html
  src/main/resources/templates/profileUpdate.html
  src/main/resources/templates/updateBoardPage.html
Labels: front

#224 Front/css
  src/main/resources/static/css/saveBoardPage.css
  src/main/resources/templates/login.html
  src/main/resources/templates/saveBoardPage.html
  src/main/resources/templates/signup.html
Labels: front

#226 관리자 페이지 페이징 수정, 페이지 이동 수정
  src/main/java/sparta/com/sappun/global/jwt/JwtAuthorizationFilter.java
  src/main/java/sparta/com/sappun/global/security/WebSecurityConfig.java
  src/main/resources/static/js/basic.js
  src/main/resources/templates/reportBoardPage.html
  src/main/resources/templates/reportCommentPage.html
Labels: front

#228 회원가입 오류 수정
  src/main/java/sparta/com/sappun/domain/user/service/UserService.java
  src/main/resources/templates/signup.html
Labels: fix

#230 [#229] Front: http페이지 내에 Js, css 병합
  src/main/resources/static/css/getBoardDetail.css
  src/main/resources/static/css/login.css
  src/main/resources/static/css/mainPage.css
  src/main/resources/static/css/profile.css
  src/main/resources/static/css/profileUpdate.css
  src/main/resources/static/css/pwUpdate.css
  src/main/resources/static/css/regionPage.css
  src/main/resources/static/css/reportBoardPage.css
  src/main/resources/static/css/reportCommentPage.css
  src/main/resources/static/css/saveBoardPage.css
  src/main/resources/static/css/signup.css
  src/main/resources/static/css/updateBoardPage.css
  src/main/resources/static/js/basic.js
  src/main/resources/templates/getBoardDetail.html
  src/main/resources/templates/login.html
  src/main/resources/templates/mainPage.html
  src/main/resources/templates/profile.html
  src/main/resources/templates/profileUpdate.html
  src/main/resources/templates/pwUpdate.html
  src/main/resources/templates/regionPage.html
  src/main/resources/templates/reportBoardPage.html
  src/main/resources/templates/reportCommentPage.html
  src/main/resources/templates/saveBoardPage.html
  src/main/resources/templates/signup.html
  src/main/resources/templates/updateBoardPage.html
Labels: front

#232 [#231] Front: 로고이미지 S3에서 받도록 수정
  src/main/resources/static/images/logo.png
  src/main/resources/templates/getBoardDetail.html
  src/main/resources/templates/login.html
  src/main/resources/templates/mainPage.html
  src/main/resources/templates/profile.html
  src/main/resources/templates/profileUpdate.html
  src/main/resources/templates/pwUpdate.html
  src/main/resources/templates/regionPage.html
  src/main/resources/templates/reportBoardPage.html
  src/main/resources/templates/reportCommentPage.html
  src/main/resources/templates/saveBoardPage.html
  src/main/resources/templates/signup.html
  src/main/resources/templates/updateBoardPage.html
Labels: front

#236 [#234] fix: jwtUtil.getTokensFromCookie NULL값 오류 처리
  src/main/java/sparta/com/sappun/domain/user/controller/UserController.java
  src/main/java/sparta/com/sappun/global/jwt/JwtAuthorizationFilter.java
Labels: fix

#238 페이지 기타 오류 수정
  src/main/resources/templates/getBoardDetail.html
  src/main/resources/templates/login.html
  src/main/resources/templates/profile.html
  src/main/resources/templates/reportBoardPage.html
  src/main/resources/templates/reportCommentPage.html
Labels: fix

#241 [#240] Front: 소셜로그인
  src/main/java/sparta/com/sappun/domain/user/controller/KakaoController.java
  src/main/java/sparta/com/sappun/domain/user/controller/NaverController.java
Labels: front

#243 [#242] Front: 소셜로그인
  src/main/resources/templates/login.html
Labels: front

#246 Front/css
  src/main/java/sparta/com/sappun/domain/user/controller/KakaoController.java
  src/main/java/sparta/com/sappun/domain/user/controller/NaverController.java
  src/main/resources/templates/getBoardDetail.html
  src/main/resources/templates/login.html
  src/main/resources/templates/updateBoardPage.html
Labels: front

#251 [#250] Front: 카카오 소셜로그인 버튼 URL 수정
  src/main/resources/templates/login.html
Labels: front

#255 [#254] Front: 소셜로그인 네이버 HTTPS -> HTTP로 변경
  src/main/resources/templates/login.html
Labels: front

#257 네이버 콜백 controller url 수정
  src/main/java/sparta/com/sappun/domain/user/controller/NaverController.java
Labels: fix

#259 [#258] fix: 네이버 소셜로그인 오류 수정
  src/main/java/sparta/com/sappun/domain/user/service/NaverService.java
Labels: fix

#261 [#260] front: 메인페이지, 관리자페이지(게시글, 댓글) 신고 스크롤바 추가
  src/main/resources/templates/mainPage.html
  src/main/resources/templates/reportBoardPage.html
  src/main/resources/templates/reportCommentPage.html
Labels: front

#263 게시글, 댓글 좋아요 응답값 수정
  src/main/java/sparta/com/sappun/domain/likeBoard/dto/response/LikeBoardSaveRes.java
  src/main/java/sparta/com/sappun/domain/likeBoard/service/LikeBoardService.java
  src/main/java/sparta/com/sappun/domain/likeComment/dto/response/LikeCommentSaveRes.java
  src/main/java/sparta/com/sappun/domain/likeComment/service/LikeCommentService.java
  src/main/resources/templates/getBoardDetail.html
  src/test/java/sparta/com/sappun/domain/likeBoard/controller/LikeBoardControllerTest.java
  src/test/java/sparta/com/sappun/domain/likeBoard/service/LikeBoardServiceTest.java
  src/test/java/sparta/com/sappun/domain/likeComment/controller/LikeCommentControllerTest.java
  src/test/java/sparta/com/sappun/domain/likeComment/service/LikeCommentServiceTest.java
Labels: test, feat, front

#267 [#266]불필요 페이지 삭제
  src/main/java/sparta/com/sappun/domain/board/dto/response/BoardToListGetAllRes.java
Labels: remove

#271 Error 수정
  src/main/java/sparta/com/sappun/domain/board/entity/Board.java
  src/main/resources/templates/updateBoardPage.html
Labels: front

#276 기본 도메인으로 메인 페이지 가도록 추가
  src/main/java/sparta/com/sappun/domain/main/MainController.java
  src/main/java/sparta/com/sappun/global/security/WebSecurityConfig.java
  src/main/resources/templates/login.html
Labels: feat

#274 [#273] feat : 댓글 좋아요, 최신순 정렬 기능 추가
  src/main/java/sparta/com/sappun/domain/board/controller/BoardController.java
  src/main/resources/templates/getBoardDetail.html
Labels: feat, front

#278 회원가입 오류 수정
  src/main/java/sparta/com/sappun/domain/user/service/UserService.java
Labels: fix

#280 트랜잭션 수정
  src/main/java/sparta/com/sappun/domain/board/service/BoardService.java
  src/main/java/sparta/com/sappun/domain/likeBoard/service/LikeBoardService.java
  src/main/java/sparta/com/sappun/domain/likeComment/service/LikeCommentService.java
  src/main/java/sparta/com/sappun/domain/reportBoard/service/ReportBoardService.java
  src/main/java/sparta/com/sappun/domain/reportComment/service/ReportCommentService.java
Labels: perf

#281 트랜잭션 수정
  src/main/java/sparta/com/sappun/domain/reportBoard/service/ReportBoardService.java
Labels: perf

#283 Front/css
  src/main/java/sparta/com/sappun/global/security/WebSecurityConfig.java
  src/main/resources/templates/getBoardDetail.html
  src/main/resources/templates/login.html
  src/main/resources/templates/mainPage.html
  src/main/resources/templates/profileUpdate.html
  src/main/resources/templates/saveBoardPage.html
  src/main/resources/templates/signup.html
  src/main/resources/templates/updateBoardPage.html
Labels: front

#284 [#282] front: 게시글 작성 페이지 [-]버튼 추가
  src/main/resources/templates/saveBoardPage.html
Labels: front

#286 Front/css
  src/main/java/sparta/com/sappun/global/security/WebSecurityConfig.java
  src/main/resources/templates/allBoardPage.html
  src/main/resources/templates/getBoardDetail.html
  src/main/resources/templates/mainPage.html
  src/main/resources/templates/profile.html
  src/main/resources/templates/profileUpdate.html
  src/main/resources/templates/pwUpdate.html
  src/main/resources/templates/regionPage.html
  src/main/resources/templates/reportBoardPage.html
  src/main/resources/templates/reportCommentPage.html
  src/main/resources/templates/saveBoardPage.html
  src/main/resources/templates/signup.html
  src/main/resources/templates/updateBoardPage.html
  src/main/resources/templates/userBoardPage.html
Labels: front

#288 [#287] Front: 게시글 댓글 수정 오류 해결
  src/main/resources/templates/getBoardDetail.html
Labels: front

#290 상수 처리
  src/main/java/sparta/com/sappun/domain/board/controller/BoardController.java
  src/main/java/sparta/com/sappun/domain/board/service/BoardService.java
  src/main/java/sparta/com/sappun/domain/comment/service/CommentService.java
  src/main/java/sparta/com/sappun/domain/likeBoard/service/LikeBoardService.java
  src/main/java/sparta/com/sappun/domain/likeComment/service/LikeCommentService.java
  src/main/java/sparta/com/sappun/domain/reportBoard/controller/ReportBoardController.java
  src/main/java/sparta/com/sappun/domain/reportBoard/service/ReportBoardService.java
  src/main/java/sparta/com/sappun/domain/reportComment/controller/ReportCommentController.java
  src/main/java/sparta/com/sappun/domain/reportComment/service/ReportCommentService.java
  src/main/java/sparta/com/sappun/domain/user/controller/KakaoController.java
  src/main/java/sparta/com/sappun/domain/user/controller/NaverController.java
  src/main/java/sparta/com/sappun/domain/user/controller/UserController.java
  src/main/java/sparta/com/sappun/domain/user/service/KakaoService.java
  src/main/java/sparta/com/sappun/domain/user/service/NaverService.java
  src/main/java/sparta/com/sappun/domain/user/service/UserService.java
  src/main/java/sparta/com/sappun/global/jwt/JwtAuthorizationFilter.java
  src/main/resources/templates/getBoardDetail.html
Labels: refactor

#292 [#291] Front: 지역 및 상세페이지 수정
  src/main/resources/templates/getBoardDetail.html
  src/main/resources/templates/regionPage.html
Labels: front

#294 [#293] Front: 전체조회 페이지 수정
  src/main/resources/templates/allBoardPage.html
Labels: front

#296 [#295] Front: 지역조회 페이지 수정
  src/main/resources/templates/regionPage.html
Labels: front

#300 프로필 등급 이미지 추가
  src/main/resources/templates/mainPage.html
  src/main/resources/templates/profile.html
Labels: front

#303 Front/css
  src/main/resources/templates/allBoardPage.html
  src/main/resources/templates/getBoardDetail.html
  src/main/resources/templates/login.html
  src/main/resources/templates/mainPage.html
  src/main/resources/templates/profile.html
  src/main/resources/templates/profileUpdate.html
  src/main/resources/templates/pwUpdate.html
  src/main/resources/templates/regionPage.html
  src/main/resources/templates/reportBoardPage.html
  src/main/resources/templates/reportCommentPage.html
  src/main/resources/templates/saveBoardPage.html
  src/main/resources/templates/signup.html
  src/main/resources/templates/updateBoardPage.html
  src/main/resources/templates/userBoardPage.html
Labels: front

#304 마이페이지 css 수정, 상세 페이지 댓글 작성자 진하게
  src/main/resources/templates/getBoardDetail.html
  src/main/resources/templates/userBoardPage.html
Labels: front

#307 Front/css
  src/main/resources/templates/getBoardDetail.html
  src/main/resources/templates/mainPage.html
Labels: front

#308 랭크 이미지 모든 페이지에 적용
  src/main/resources/templates/allBoardPage.html
  src/main/resources/templates/getBoardDetail.html
  src/main/resources/templates/profileUpdate.html
  src/main/resources/templates/regionPage.html
  src/main/resources/templates/reportBoardPage.html
  src/main/resources/templates/reportCommentPage.html
  src/main/resources/templates/saveBoardPage.html
  src/main/resources/templates/updateBoardPage.html
  src/main/resources/templates/userBoardPage.html
Labels: front

#310 [#309] Front: 게시글 작성 페이지 UI 수정
  src/main/resources/templates/saveBoardPage.html
Labels: front

#312 쿠키 시간 2시간으로 설정
  src/main/java/sparta/com/sappun/domain/user/controller/KakaoController.java
  src/main/java/sparta/com/sappun/domain/user/controller/NaverController.java
  src/main/java/sparta/com/sappun/domain/user/controller/UserController.java
  src/main/java/sparta/com/sappun/global/jwt/JwtAuthorizationFilter.java
Labels: fix

#314 [#313] front: 폰트 추가
  src/main/resources/templates/allBoardPage.html
  src/main/resources/templates/getBoardDetail.html
  src/main/resources/templates/regionPage.html
  src/main/resources/templates/saveBoardPage.html
  src/main/resources/templates/updateBoardPage.html
  src/main/resources/templates/userBoardPage.html
Labels: front

#316 [#315] front: 폰트 긴급적용
  src/main/resources/templates/getBoardDetail.html
Labels: front

#319 [#318] feat: 전체 게시글 조회에서 신고누적 5회 이상 조회대상에서 제외
  src/main/java/sparta/com/sappun/domain/board/repository/BoardRepository.java
  src/main/java/sparta/com/sappun/domain/board/service/BoardService.java
Labels: feat

#321 Front/css
  src/main/resources/templates/updateBoardPage.html
Labels: front

#323 지도 파일 외에 이미지 파일을 추가할 수 있도록 추가
  src/main/java/sparta/com/sappun/domain/board/controller/BoardController.java
  src/main/java/sparta/com/sappun/domain/board/dto/request/BoardSaveReq.java
  src/main/java/sparta/com/sappun/domain/board/dto/request/BoardUpdateReq.java
  src/main/java/sparta/com/sappun/domain/board/dto/response/BoardGetRes.java
  src/main/java/sparta/com/sappun/domain/board/dto/response/ImageGetRes.java
  src/main/java/sparta/com/sappun/domain/board/entity/Board.java
  src/main/java/sparta/com/sappun/domain/board/entity/Image.java
  src/main/java/sparta/com/sappun/domain/board/repository/ImageRepository.java
  src/main/java/sparta/com/sappun/domain/board/service/BoardService.java
  src/main/resources/templates/getBoardDetail.html
  src/main/resources/templates/saveBoardPage.html
  src/main/resources/templates/updateBoardPage.html
  src/test/java/sparta/com/sappun/domain/board/controller/BoardControllerTest.java
Labels: feat

#324 페이지별 폰트 변경
  src/main/resources/templates/allBoardPage.html
  src/main/resources/templates/getBoardDetail.html
  src/main/resources/templates/login.html
  src/main/resources/templates/mainPage.html
  src/main/resources/templates/profile.html
  src/main/resources/templates/profileUpdate.html
  src/main/resources/templates/pwUpdate.html
  src/main/resources/templates/regionPage.html
  src/main/resources/templates/saveBoardPage.html
  src/main/resources/templates/signup.html
  src/main/resources/templates/updateBoardPage.html
  src/main/resources/templates/userBoardPage.html
Labels: front

#326 [#325] Front: 저장페이지 UI 변경
  src/main/resources/templates/saveBoardPage.html
Labels: front

#328 [#327] Front: 게시글 저장, 수정 페이지 UI 변경
  src/main/resources/templates/saveBoardPage.html
  src/main/resources/templates/updateBoardPage.html
Labels: front

#330 토큰 자동 로그인 오류 수정
  src/main/java/sparta/com/sappun/domain/user/controller/UserController.java
  src/main/java/sparta/com/sappun/domain/user/service/KakaoService.java
  src/main/java/sparta/com/sappun/domain/user/service/NaverService.java
  src/main/java/sparta/com/sappun/global/jwt/JwtAuthorizationFilter.java
  src/main/java/sparta/com/sappun/global/jwt/JwtUtil.java
  src/main/java/sparta/com/sappun/global/redis/RedisUtil.java
  src/main/java/sparta/com/sappun/global/security/UserDetailsServiceImpl.java
Labels: fix

#332 댓글 수정, 게시글 제목 오류 수정
  src/main/resources/templates/getBoardDetail.html
  src/main/resources/templates/saveBoardPage.html
Labels: fix

#334 [#333] front: 전체, 지역, 유저 게시글 목록 최신순, 좋아요순 버튼 스타일수정
  src/main/resources/templates/allBoardPage.html
  src/main/resources/templates/getBoardDetail.html
  src/main/resources/templates/regionPage.html
  src/main/resources/templates/userBoardPage.html
Labels: front

#336 게시판 상세조회페이지 UI 수정 및 댓글 조회 수정
  src/main/resources/templates/getBoardDetail.html
Labels: front

#341 전체 페이징 처리 오류 수정
  src/main/java/sparta/com/sappun/domain/board/controller/BoardController.java
Labels: fix

#346 지도 자동 첨부 기능 구현
  src/main/java/sparta/com/sappun/domain/board/controller/BoardController.java
  src/main/java/sparta/com/sappun/domain/board/dto/request/BoardSaveReq.java
  src/main/java/sparta/com/sappun/domain/board/dto/request/BoardUpdateReq.java
  src/main/java/sparta/com/sappun/domain/board/service/BoardService.java
  src/main/resources/application.yml
  src/main/resources/templates/saveBoardPage.html
  src/main/resources/templates/updateBoardPage.html
Labels: feat

#348 [#345] Fix: yml 수정
  src/main/resources/application.yml
Labels: fix

#347 Front/css
  src/main/resources/templates/allBoardPage.html
  src/main/resources/templates/getBoardDetail.html
  src/main/resources/templates/mainPage.html
  src/main/resources/templates/profile.html
  src/main/resources/templates/profileUpdate.html
  src/main/resources/templates/regionPage.html
  src/main/resources/templates/saveBoardPage.html
  src/main/resources/templates/signup.html
  src/main/resources/templates/updateBoardPage.html
  src/main/resources/templates/userBoardPage.html
Labels: front

#351 프로필 이미지 보이도록 수정
  src/main/java/sparta/com/sappun/domain/board/dto/response/BoardGetRes.java
  src/main/java/sparta/com/sappun/domain/board/service/BoardServiceMapper.java
  src/main/java/sparta/com/sappun/domain/comment/dto/response/CommentGetRes.java
  src/main/resources/templates/getBoardDetail.html
Labels: front

#353 #352 페이지 이동버튼 동적으로 5개 제한 기능 구현 / 전체,지역,유저 게시글
  src/main/resources/templates/allBoardPage.html
  src/main/resources/templates/regionPage.html
  src/main/resources/templates/userBoardPage.html
Labels: front

#354 Front/css
  src/main/resources/templates/allBoardPage.html
  src/main/resources/templates/getBoardDetail.html
  src/main/resources/templates/login.html
  src/main/resources/templates/mainPage.html
  src/main/resources/templates/profile.html
  src/main/resources/templates/profileUpdate.html
  src/main/resources/templates/pwUpdate.html
  src/main/resources/templates/regionPage.html
  src/main/resources/templates/reportBoardPage.html
  src/main/resources/templates/reportCommentPage.html
  src/main/resources/templates/saveBoardPage.html
  src/main/resources/templates/signup.html
  src/main/resources/templates/updateBoardPage.html
  src/main/resources/templates/userBoardPage.html
Labels: front

#358 프로필 이미지 조회 기능 오류 수정
  src/main/java/sparta/com/sappun/global/security/WebSecurityConfig.java
  src/main/resources/templates/getBoardDetail.html
Labels: fix

#361 Best 게시글 좋아요 버튼 및 공지사항 및 푸터 추가
  src/main/resources/templates/mainPage.html
Labels: front

#362 레디스 관련 오류 수정 시도
  src/main/java/sparta/com/sappun/global/redis/RedisConfig.java
  src/main/java/sparta/com/sappun/global/redis/RedisUtil.java
Labels: fix

#364 쿠키 도메인 설정
  src/main/java/sparta/com/sappun/domain/user/controller/KakaoController.java
  src/main/java/sparta/com/sappun/domain/user/controller/NaverController.java
  src/main/java/sparta/com/sappun/domain/user/controller/UserController.java
  src/main/java/sparta/com/sappun/global/jwt/JwtAuthorizationFilter.java
Labels: fix

#365 쿠키 도메인 설정 오류 수정
  src/main/java/sparta/com/sappun/domain/user/controller/KakaoController.java
  src/main/java/sparta/com/sappun/domain/user/controller/NaverController.java
  src/main/java/sparta/com/sappun/domain/user/controller/UserController.java
  src/main/java/sparta/com/sappun/global/jwt/JwtAuthorizationFilter.java
Labels: fix

#366 쿠키 오류로 복구
  src/main/java/sparta/com/sappun/domain/user/controller/KakaoController.java
  src/main/java/sparta/com/sappun/domain/user/controller/NaverController.java
  src/main/java/sparta/com/sappun/domain/user/controller/UserController.java
  src/main/java/sparta/com/sappun/global/jwt/JwtAuthorizationFilter.java
Labels: fix

#368 사용자 테스트 코드 보완
  src/main/java/sparta/com/sappun/domain/user/controller/UserController.java
  src/main/resources/templates/profileUpdate.html
  src/main/resources/templates/signup.html
  src/test/java/sparta/com/sappun/domain/user/controller/UserControllerTest.java
  src/test/java/sparta/com/sappun/domain/user/repository/UserRepositoryTest.java
  src/test/java/sparta/com/sappun/domain/user/service/UserServiceTest.java
Labels: test

#373 [#372] fix : 좋아요 페이지 이동버튼 url 수정
  src/main/resources/templates/likeBoardPage.html
Labels: fix

#374 footer 전체 페이지 적용 및 상단 버튼 UI 수정
  src/main/java/sparta/com/sappun/domain/likeBoard/controller/LikeBoardController.java
  src/main/java/sparta/com/sappun/domain/reportBoard/controller/ReportBoardController.java
  src/main/resources/templates/allBoardPage.html
  src/main/resources/templates/getBoardDetail.html
  src/main/resources/templates/likeBoardPage.html
  src/main/resources/templates/login.html
  src/main/resources/templates/mainPage.html
  src/main/resources/templates/profile.html
  src/main/resources/templates/profileUpdate.html
  src/main/resources/templates/pwUpdate.html
  src/main/resources/templates/regionPage.html
  src/main/resources/templates/reportBoardPage.html
  src/main/resources/templates/reportCommentPage.html
  src/main/resources/templates/saveBoardPage.html
  src/main/resources/templates/signup.html
  src/main/resources/templates/updateBoardPage.html
  src/main/resources/templates/userBoardPage.html
Labels: fix, front

#378 [#376] front: 지역 선택 시 해당 지역으로 지도 위치 이동, 자치 오타 수정
  src/main/java/sparta/com/sappun/domain/board/entity/RegionEnum.java
  src/main/resources/templates/allBoardPage.html
  src/main/resources/templates/getBoardDetail.html
  src/main/resources/templates/likeBoardPage.html
  src/main/resources/templates/login.html
  src/main/resources/templates/mainPage.html
  src/main/resources/templates/regionPage.html
  src/main/resources/templates/reportBoardPage.html
  src/main/resources/templates/reportCommentPage.html
  src/main/resources/templates/saveBoardPage.html
  src/main/resources/templates/signup.html
  src/main/resources/templates/updateBoardPage.html
  src/main/resources/templates/userBoardPage.html
Labels: fix, front

#380 게시글 테스트 코드 보완
  src/main/java/sparta/com/sappun/domain/board/controller/BoardController.java
  src/main/java/sparta/com/sappun/domain/board/dto/request/BoardSaveReq.java
  src/main/java/sparta/com/sappun/domain/board/dto/request/BoardUpdateReq.java
  src/main/java/sparta/com/sappun/domain/board/entity/Image.java
  src/main/java/sparta/com/sappun/domain/board/repository/BoardRepository.java
  src/main/java/sparta/com/sappun/domain/board/service/BoardService.java
  src/test/java/sparta/com/sappun/domain/board/controller/BoardControllerTest.java
  src/test/java/sparta/com/sappun/domain/board/repository/BoardRepositoryTest.java
  src/test/java/sparta/com/sappun/domain/board/service/BoardServiceTest.java
  src/test/java/sparta/com/sappun/test/BoardTest.java
Labels: test

#383 Front/css
  src/main/resources/templates/mainPage.html
  src/main/resources/templates/saveBoardPage.html
  src/main/resources/templates/updateBoardPage.html
Labels: front

#385 비밀번호 수정 페이지 UI변경
  src/main/resources/templates/login.html
  src/main/resources/templates/pwUpdate.html
Labels: front

#387 댓글, 좋아요, 신고 테스트 보완
  src/main/java/sparta/com/sappun/domain/likeBoard/repository/LikeBoardRepository.java
  src/test/java/sparta/com/sappun/domain/likeBoard/repository/LikeBoardRepositoryTest.java
  src/test/java/sparta/com/sappun/domain/likeComment/controller/LikeCommentControllerTest.java
  src/test/java/sparta/com/sappun/domain/reportBoard/repository/ReportBoardRepositoryTest.java
  src/test/java/sparta/com/sappun/domain/reportComment/contorller/ReportCommentControllerTest.java
  src/test/java/sparta/com/sappun/domain/reportComment/repository/ReportCommentRepositoryTest.java
  src/test/java/sparta/com/sappun/domain/reportComment/service/ReportCommentServiceTest.java
Labels: test

#389 신고 테스트 보완
  src/test/java/sparta/com/sappun/domain/reportBoard/service/ReportBoardServiceTest.java
Labels: test

#390 Front/css
  src/main/resources/templates/allBoardPage.html
  src/main/resources/templates/getBoardDetail.html
  src/main/resources/templates/likeBoardPage.html
  src/main/resources/templates/mainPage.html
  src/main/resources/templates/regionPage.html
  src/main/resources/templates/reportBoardPage.html
  src/main/resources/templates/reportCommentPage.html
  src/main/resources/templates/userBoardPage.html
Labels: front

#393 게시글 작성 수정시 이미지파일 업로드 제한 (장당 10MB)
  src/main/java/sparta/com/sappun/global/response/ResultCode.java
  src/main/java/sparta/com/sappun/global/validator/S3Validator.java
  src/main/java/sparta/com/sappun/infra/s3/S3Util.java
  src/main/resources/application.yml
  src/main/resources/templates/saveBoardPage.html
  src/main/resources/templates/updateBoardPage.html
Labels: feat, front

#394 게시판 repository QueryDsl 적용
  .gitignore
  build.gradle
  src/main/java/sparta/com/sappun/domain/board/controller/BoardController.java
  src/main/java/sparta/com/sappun/domain/board/repository/BoardRepository.java
  src/main/java/sparta/com/sappun/domain/board/repository/BoardRepositoryCustom.java
  src/main/java/sparta/com/sappun/domain/board/repository/BoardRepositoryImpl.java
  src/main/java/sparta/com/sappun/global/config/QuerydslConfig.java
  src/main/java/sparta/com/sappun/global/jwt/JwtAuthorizationFilter.java
  src/test/java/sparta/com/sappun/domain/board/repository/BoardRepositoryTest.java
Labels: refactor, perf
