Repository Sappun-Walk/Sappun, pull requests merged in 2024-02, with the labels that each got.

#405 [#404] 게시글 신고, 댓글 신고 queryDsl 적용
  src/main/java/sparta/com/sappun/domain/reportBoard/repository/ReportBoardRepository.java
  src/main/java/sparta/com/sappun/domain/reportBoard/repository/ReportBoardRepositoryCustom.java
  src/main/java/sparta/com/sappun/domain/reportBoard/repository/ReportBoardRepositoryImpl.java
  src/main/java/sparta/com/sappun/domain/reportComment/repository/ReportCommentRepository.java
  src/main/java/sparta/com/sappun/domain/reportComment/repository/ReportCommentRepositoryCustom.java
  src/main/java/sparta/com/sappun/domain/reportComment/repository/ReportCommentRepositoryImpl.java
Labels: perf

#407 Redis 비밀번호 설정
  src/main/java/sparta/com/sappun/global/redis/RedisConfig.java
Labels: fix

#414 [#413] ReadMe 작성
  README.md
  src/main/resources/static/images/Architecture.png
  src/main/resources/static/images/ERD.png
Labels: docs

#417 이미지 용량제한 및 리사이징 (댓글, 프로필)
  src/main/resources/templates/getBoardDetail.html
  src/main/resources/templates/profileUpdate.html
  src/main/resources/templates/saveBoardPage.html
  src/main/resources/templates/signup.html
  src/main/resources/templates/updateBoardPage.html
Labels: feat, front

#419 Update README.md
  README.md
Labels: docs

#421 [#420] docs: ReadMe Update
  README.md
Labels: docs

#423 Social test
  src/main/java/sparta/com/sappun/domain/user/dto/request/KakaoInsertReq.java
  src/main/resources/application-test.yml
  src/test/java/sparta/com/sappun/domain/user/controller/KakaoControllerTest.java
  src/test/java/sparta/com/sappun/domain/user/controller/NaverControllerTest.java
Labels: test

#424 Front/css
  src/main/resources/static/js/getBoardDetail.js
  src/main/resources/static/js/profileUpdate.js
  src/main/resources/static/js/saveBoardPage.js
  src/main/resources/static/js/signup.js
  src/main/resources/static/js/updateBoardPage.js
  src/main/resources/templates/getBoardDetail.html
Labels: fix

#426 [#425] fix: js 수정
  src/main/resources/static/js/getBoardDetail.js
  src/main/resources/static/js/profileUpdate.js
  src/main/resources/static/js/saveBoardPage.js
  src/main/resources/static/js/signup.js
  src/main/resources/static/js/updateBoardPage.js
Labels: fix, front
